### ISSUE TITLE
Image is not displayed on github

### ISSUE THREAD

**Issue by DASenkiv** [socketio/socket.io-website#115]
Hello! 
On https://github.com/socketio/socket.io-website/blob/master/source/docs/internals.md, string 21 contains link to image. This path to image doesn`t exist on github.  Is this link only for site? May be should stored image on github too?

**Comment by 64J0** [comment]
Bump, there are other images with the same problem. I think it's because those images have been moved to https://github.com/socketio/socket.io-website/blob/master/diagrams/ with excalidraw extension.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks for the heads-up :+1:
