### ISSUE TITLE
Error on create signed app

### ISSUE THREAD

**Issue by Aryan-mor** [socketio/socket.io-website#120]
Hello, i use androidX
When i create signed app, receive error.

![Snipaste_2019-06-02_11-03-26](https://user-images.githubusercontent.com/22844436/58757714-57cfd300-8526-11e9-8da4-baea9a7a6b17.png)

After search to used libraries, i found error on socket.io library.
Please check this.

**Comment by rupesh-kumar-lpu** [comment]
try 
```
//Dependencies:
implementation('io.socket:socket.io-client:1.0.0') {
exclude group: 'org.json', module: 'json'
}
```
notify me back if it works!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
