### ISSUE TITLE
Video missing in get-started chat example under 'Emitting events' heading

### ISSUE THREAD

**Issue by Haider8** [socketio/socket.io-website#123]

**Comment by pushp1997** [comment]
Hi, I would like to work on this issue.

**Comment by Haider8** [comment]
@pushp1997 Go ahead 👍

**Comment by pushp1997** [comment]
Hey thanks, can you provide the video source @Haider8 ?

**Comment by darrachequesne** [comment]
The video seems to work fine on Firefox / Chrome.

![image](https://user-images.githubusercontent.com/13031701/87016963-ac388e00-c1cf-11ea-8e07-bd9b4f63fc13.png)

 What is your setup? Do you get any error in the console?

**Comment by Haider8** [comment]
Working fine now
