### ISSUE TITLE
socket.io sets cross-site cookie without same-site attribute

### ISSUE THREAD

**Issue by sanmiguel2019** [socketio/socket.io-website#136]
Chrome console displays this warning for cookie called 'io':

`A cookie associated with a cross-site resource at http://mydomain.eu/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

Other people have the same problem:
[https://stackoverflow.com/questions/58557911/socket-io-sets-cross-site-cookie-without-same-site-attribute](https://stackoverflow.com/questions/58557911/socket-io-sets-cross-site-cookie-without-same-site-attribute)

**Comment by darrachequesne** [comment]
For future readers: the cookie was removed in Socket.IO v3

Documentation:
- https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#No-more-cookie-by-default
- https://socket.io/docs/v3/server-initialization/#cookie
