### ISSUE TITLE
chat demo is using deprecated feature of Express

### ISSUE THREAD

**Issue by ryanmjacobs** [socketio/socket.io-website#16]
On the demo http://socket.io/get-started/chat/ in the section titled **Integrating Socket.IO**,

``` javascript
res.sendfile('index.html');
```

generates the error: `express deprecated res.sendfile: Use res.sendFile instead index.js:6:9`

It can fixed by replacing the line with

``` javascript
res.sendFile(__dirname + '/index.html');    
```

**Comment by paradite** [comment]
maybe we can use update the code on website to https://github.com/socketio/socket.io/blob/master/examples/chat/index.js 

```
// Routing
app.use(express.static(__dirname + '/public'));
```

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
