### ISSUE TITLE
cant emit a specific user with its id

### ISSUE THREAD

**Issue by mohammadjavad948** [socketio/socket.io-website#165]
everything works fine but i cant emit a user with its id 
here is a part of my server code: 

`io.on('connect', (socket) => {
   console.log('someone connected!');
   
   io.to(socket.id).emit('setXO', 'X');
});`

and here is my client code: 

`this.socket.on('setXO', (data) => {
      console.log(data);
 });`

i get nothing when i run the code (other emits and events works fine)

**Comment by darrachequesne** [comment]
`socket.emit(...)` should work:

```js
io.on('connect', (socket) => {
  console.log('someone connected!');

  socket.emit('setXO', 'X');
});
```
