### ISSUE TITLE
issue with client side 

### ISSUE THREAD

**Issue by hayderjebur** [socketio/socket.io-website#172]
I am having issue with websocket client side after initialize socket in react component "socket = io(localhost:3000);" it keeps log error in console of the browser *polling-xhr.js:265 POST http://localhost:3000/socket.io/?EIO=3&transport=polling&t=NHxO42s 404 (Not Found) anyone had the issue... thank you

**Comment by darrachequesne** [comment]
For future readers, please check https://socket.io/docs/v4/troubleshooting-connection-issues/
