### ISSUE TITLE
Get Started page missing information

### ISSUE THREAD

**Issue by AuracleTech** [socketio/socket.io-website#182]
On the [Get Started](https://github.com/socketio/socket.io-website/blob/master/source/get-started/chat.md) page, there's almost everything everyone would need.
But I believe there's no 1 to 1 response example.
The examples are : 
Sender client -> Server Console print
Sender client -> Server ->All Clients
Sender client -> Server ->All clients except sender
but no Sender client -> Server -> Sender client ( A simple exchange ).

How to do a io.emit without it going to everyone?

Example Client request sensitive data -> Server sends back data _to this client only_ -> Client receive sensitive data
(Also is there a way to secure it or is it done by default)

If I missed it I apologize, else I'll wait your answers :) !

**Found answer on** https://stackoverflow.com/questions/24100218/socket-io-send-packet-to-sender-only
Can you guys add this info on OG webpage

**Comment by darrachequesne** [comment]
Yes you are right, there are a few steps that are missing:

- acknowledgements:

```js
// client-side
socket.emit("question", "?", (response) => {
  console.log(response); // 42
});

// server-side
socket.on("question", (content, callback) => {
  console.log(content); // ?
  callback(42);
});
```

- and peer to peer chat:

```js
// client-side
socket.emit("sendTo", socketId, payload);

// server-side
socket.on("sendTo", (socketId, payload) => {
  socket.to(socketId).emit("sendTo", payload);
});
```

Let's add this.

**Comment by AuracleTech** [comment]
I made my own docs for me and my pals on my discord
![Screenshot_20201023-185552~2](https://user-images.githubusercontent.com/40531871/97060585-c3727000-1561-11eb-8889-b9d4ef4c4f03.png)
![Screenshot_20201023-185528~2](https://user-images.githubusercontent.com/40531871/97060575-bd7c8f00-1561-11eb-94b1-69142fe9bb6a.png)
![Screenshot_20201023-185519~2](https://user-images.githubusercontent.com/40531871/97060560-b6558100-1561-11eb-8d49-4825b05c3ff6.png)

**Comment by darrachequesne** [comment]
For future readers: please see the example [here](https://socket.io/get-started/private-messaging-part-1/).
