### ISSUE TITLE
Navigation bar hidden on small devices

### ISSUE THREAD

**Issue by googol88** [socketio/socket.io-website#185]
The navigation bar, containing the search bar and links to documentation and resources, becomes hidden when the viewport width becomes too small. There's no toggle or anything, it just becomes hidden and completely inaccessible. Other elements in the UI are missing as well on small viewport sizes, including the sidebar in the documentation. This problem is actually site-wide, on the index and in all of the docs, but I assume that fixing it shouldn't be too difficult.

**Comment by nhykhlb** [comment]
I want to fix it.Can you please assign me this issue.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-website/commit/bf2988b831a21e473526e53b9fad102eb9d784fd
