### ISSUE TITLE
Feature request: please add instructions how to use SSL connection 

### ISSUE THREAD

**Issue by inglesuniversal** [socketio/socket.io-website#186]
Now that the script runs locally I have not found any reference on how to install it using  an https connection for production purposes. Thanks.

**Comment by matiaslopezd** [comment]
@inglesuniversal This is related to Express and HTTPS, not Feathers. Here is an example how to: [Node + Express + LetsEncrypt](https://itnext.io/node-express-letsencrypt-generate-a-free-ssl-certificate-and-run-an-https-server-in-5-minutes-a730fbe528ca) . Remember is better to have Node behind of proxy like Nginx!

**Comment by darrachequesne** [comment]
You simply need to attach the Socket.IO server to a HTTPS server:

```js
const fs = require('fs');
const server = require('https').createServer({
  key: fs.readFileSync('/tmp/key.pem'),
  cert: fs.readFileSync('/tmp/cert.pem')
});
const options = { /* ... */ };
const io = require('socket.io')(server, options);

io.on('connection', socket => { /* ... */ });

server.listen(3000);
```

Documented here: https://socket.io/docs/v3/server-initialization/#Attached-to-an-existing-HTTP-server

All options can be found here: https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener
