### ISSUE TITLE
Sponsors and Open graph

### ISSUE THREAD

**Issue by adaptive** [socketio/socket.io-website#189]
Sponsorship is vital, it is important to feature sponsors on socket.io page, including them on the open graph, that is something that provides the wrong message.

I was going to tweet about Socket.io 3 👏, congrats.
Showing gambling is way off.

<img width="530" alt="Screen Shot 2020-11-06 at 12 20 49 PM" src="https://user-images.githubusercontent.com/17833/98366874-95466300-202c-11eb-955c-70778e424bec.png">

**Comment by darrachequesne** [comment]
Oh. That's totally not cool. I'll check that.

**Comment by darrachequesne** [comment]
It should be fixed by https://github.com/socketio/socket.io-website/commit/afcd8d7f6229311d6c43b043bb69d9137317b282.

Thanks a lot for the heads up.

**Comment by adaptive** [comment]
Perfect...🍾
<img width="462" alt="Screen Shot 2020-11-07 at 12 38 20 PM" src="https://user-images.githubusercontent.com/17833/98441440-377e4d80-20f6-11eb-9ead-38f5b75213c6.png">
