### ISSUE TITLE
Code Formatting, Docs Page

### ISSUE THREAD

**Issue by helenvholmes** [socketio/socket.io-website#19]
![screen shot 2015-02-06 at 12 11 45 pm](https://cloud.githubusercontent.com/assets/1720093/6083945/b9057a38-adfa-11e4-915a-42c7f57228c3.png)

Because this is in a code block, it's spitting out ```&amp;#039;```, for example, instead of &' (assuming that was the intent).

Showing up in Chrome Version 40.0.2214.111 (64-bit), currently up-to-date.

**Comment by 1j01** [comment]
:+1: This is pretty ugly.
It's being double-encoded, from `'` to `&#039;` to `&amp;#039;`
```
// note, io.listen(&lt;port&gt;) will create a http server for you
var io = require(&amp;#039;socket.io&amp;#039;)(80);

io.on(&amp;#039;connection&amp;#039;, function (socket) {
  io.emit(&amp;#039;this&amp;#039;, { will: &amp;#039;be received by everyone&amp;#039;});

  socket.on(&amp;#039;private message&amp;#039;, function (from, msg) {
    console.log(&amp;#039;I received a private message by &amp;#039;, from, &amp;#039; saying &amp;#039;, msg);
  });

  socket.on(&amp;#039;disconnect&amp;#039;, function () {
    io.sockets.emit(&amp;#039;user disconnected&amp;#039;);
  });
});
```

**Comment by paradite** [comment]
@helenvholmes are you still having this issue? Unable to reproduce now.

**Comment by helenvholmes** [comment]
@paradite No, looks like it's been taken care of. 

I'll close out the issue.
