### ISSUE TITLE
Migration guide missing some changes

### ISSUE THREAD

**Issue by saltire** [socketio/socket.io-website#190]
Congrats on releasing v3!

Not sure if the list of changes in the migration guide is meant to be exhaustive, but I did find (the hard way) one little thing that was missing:

_Namespace#clients() is renamed to Namespace#allSockets() and now returns a Promise_

**Comment by darrachequesne** [comment]
> Congrats on releasing v3!

Thanks!

You are absolutely right, the change was missing from the migration guide, sorry for that... Added [here](https://socket.io/docs/migrating-from-2-x-to-3-0/#Namespace-clients-is-renamed-to-Namespace-allSockets-and-now-returns-a-Promise).
