### ISSUE TITLE
Server is not a constructor

### ISSUE THREAD

**Issue by GaikwadPratik** [socketio/socket.io-website#202]
I'm following code mentioned in `Miscellaneous` section on https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html
 in a Typescript application with testify server as backend.

```
import { Server, Socket } from "socket.io";
const io = new Server(8080);
``` 

I'm getting below error:

```
    TypeError: socket_io_1.Server is not a constructor
```

version 3.0.4 is being used. Can someone please help me understand what am I missing?

**Comment by darrachequesne** [comment]
Hi! It seems I can't reproduce the issue with the example here: https://github.com/socketio/socket.io/tree/master/examples/typescript

Could you please check?

**Comment by GaikwadPratik** [comment]
@darrachequesne ,

Thank you for quick response. I tried the example mentioned above. It works in a separate project. But in my existing project when I'm importing the same code, it gave me same error.

I tried with below code:

```
const io = new Server(port number);
const io = new Server(restify.httpServer);
const io = new Server()
```

in all 3 instances I got the same error. I would really appreciate any pointers

**Comment by GaikwadPratik** [comment]
@darrachequesne ,

Somehow older version was pulled into `node_modules`. Once I deleted `node_modules` and reinstall all the packages, it started working. Thanks for your help!

**Comment by nileshyadavme** [comment]
you are trying to create a new instance of the Socket.IO server using the SocketIO constructor, but there is no such constructor.
you need to use the Server class instead.

const { Server } = require('socket.io');
const server = new Server();
