### ISSUE TITLE
The API documentation isn't thorough

### ISSUE THREAD

**Issue by elisee** [socketio/socket.io-website#21]
Hey! Thanks for a great library.

Here are some undocumented features from the API that could be mentioned on http://socket.io/docs.
- **Namespace#in** is like **Socket#in** but namespaced
- **Namespace#emit** is like **Socket#emit** but for a namespace (or room in a namespace)
- **Socket#handshake** provides [various useful bits of info](https://github.com/Automattic/socket.io/blob/3f72dd3322bcefff07b5976ab817766e421d237b/lib/socket.js#L107)

There are more (Namespace#adapter, for instance).

Overall, I think socket.io's documentation would be much nicer if there was a complete list of all public members & methods in a single location. Right now, the API is partially documented over these three pages: "Server API", "Client API" and "Rooms and namespaces" and they are more like prose than a reference. I often end up having to go spelunking in the source code to see the exact shape of the API.

The DefinitelyTyped [TypeScript definition file for socket.io](https://github.com/borisyankov/DefinitelyTyped/blob/master/socket.io/socket.io.d.ts) is very useful (though it lacks some minimal comments) but it's incomplete too, probably because it was built from the documented API rather than ground truth.

Anyway, I hope you'll take those comments under consideration, and once again, thanks for all the amazing work!

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed now: https://socket.io/docs/v4/

If you find anything missing, please ping me.
