### ISSUE TITLE
Running both versions of socket.io does not work properly

### ISSUE THREAD

**Issue by thatsmydoing** [socketio/socket.io-website#210]
The migration docs suggest the following:

> You could also take advantage of the [package aliases](https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md) feature of your favorite package manager in order to have both versions running in parallel:
> 
> ```js
> // npm i socket.io@2 socket.io-next@npm:socket.io@3
> // or yarn add socket.io@2 socket.io-next@npm:socket.io@3
> const httpServer = require("http").createServer();
> const io = require("socket.io")(httpServer);
> const ioNext = require("socket.io-next")(httpServer, {
>   path: "/socket.io-next/"
> });
> ```

while it does work and both socket.io instances run, websocket connections don't really work. The [upgrade handlers](https://github.com/socketio/engine.io/blob/e5b307c16d8e7594fcec4eb23508f23f78546dc6/lib/server.js#L429-L443) of both interfere with each other. I think this can be solved by having one of them have `destroyUpgrade: false` as an option but I have not tested this. I went with a more involved option to run both on the same server with the same path.

**Comment by darrachequesne** [comment]
As of `socket.io@3.1.0`, a v3 server is able to communicate with a v2 client: https://socket.io/blog/socket-io-3-1-0/

The migration guide was updated accordingly: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#How-to-upgrade-an-existing-production-deployment

Thanks for the heads-up!
