### ISSUE TITLE
Best way to add an event listener to save resources

### ISSUE THREAD

**Issue by shunz19** [socketio/socket.io-website#213]
So i'm trying to know how javascript handles function.

if i have a code like this:
```
io.on("connection", function(socket) {
  socket.on("hi", function(data) {
    socket.emit("emit", "hey")
  })
})
```
What's in my mind is that each new connection, javascript will create another function for the "hi" event. So what I'm currently doing in my app is like this:
```
function hi(data) {
    this.emit("emit", "hey")
}

io.on("connection", function(socket) {
  socket.on("hi", hi)
})
```
This way javascript will just reuse the function hi instead of instancing a new one?? I'm not sure if this is necessary but I want to consume less resources as much as possible because I'm thinking about what will happen when the server have thousand of connections.

**Comment by darrachequesne** [comment]
Follow-up discussion: https://github.com/socketio/socket.io/discussions/3771
