### ISSUE TITLE
 what happened in socket io . 

### ISSUE THREAD

**Issue by Mohammedkhateb** [socketio/socket.io-website#215]
error io.socket.engineio.client.EngineIOException: xhr poll error

**Comment by darrachequesne** [comment]
We'll need a lot more details in order to be able to help you. Could you please explain your issue?

**Comment by Mohammedkhateb** [comment]
hello socket io developers

my node js server is running successfully
on port 9000

socket io client connected successfully from web

but in android device
return connection time out

xhr polling error

and when i change transport to websocket

return
connection time out

im very sad for this proplem  I love socket io but its not work

on android i added internet permission
and added
uses... clear... trafic... - > true

i need help please

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
