### ISSUE TITLE
No Mobile Nav

### ISSUE THREAD

**Issue by ColeyG** [socketio/socket.io-website#223]
The docs are unusable on mobile without a navbar or other way to move between pages!

**Comment by darrachequesne** [comment]
Thanks for reporting this. This issue is quite low-priority on our side (as most users are browsing the documentation from a desktop browser), would you have time to fix it? I'll be happy to merge your pull request.

**Comment by ColeyG** [comment]
I'll take a look at getting a local version spun up and tinker around with it for sure :)

**Comment by ColeyG** [comment]
I've forked your repo and have an MR under way :)

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-website/commit/bf2988b831a21e473526e53b9fad102eb9d784fd
