### ISSUE TITLE
Mangled Examples

### ISSUE THREAD

**Issue by d3x0r** [socketio/socket.io-website#231]
Resulting from this change that artibrarily quoted values in samples....

https://github.com/socketio/socket.io-website/commit/ad42e89ac14d70a4dc75d6c2866fe16686a41ae1

This page... has quotes around eiows, which the code expects that to be a valid constructor, which a string is not.

https://socket.io/docs/v3/server-installation/#Other-WebSocket-server-implementations
And the provided example does NOT work.

This seems to be a correct example.

```
const sockIO = require( "socket.io" );
const eiows = require( "eiows" );
const io = require( "socket.io" )( 3000, {wsEngine:eiows.Server } );

io.on( "connection", (socket)=>{
	socket.on( "blah", ( what )=>{
        	console.log( "Blah?", what );
        } );
} );
```

**Comment by darrachequesne** [comment]
Hi! We're in the process of updating the website after the release of Socket.IO v4, and the `wsEngine` option has indeed been updated: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#wsEngine-option

**Comment by d3x0r** [comment]
Okay that was just a guess on my part - even after using it that way- although it appears to start - the server is terminating the connection with a simple nodejs client... so I think maybe there's more to it....

**Comment by d3x0r** [comment]
It's uhmm actually a change in engine.io 5.0 not really a webpack issue?

https://www.npmjs.com/package/eiows has an updated sample...

```
var fs = require('fs');
var https = require('https');

var ssl_options = {
    key: fs.readFileSync('server.key'),
    cert: fs.readFileSync('server.crt'),
};

var server = https.createServer(ssl_options);

server.listen(1443);

var io = require("socket.io")(server, {
    wsEngine: require("eiows").Server,
    perMessageDeflate: {
        threshold: 32768
    }
});

io.on("connection", function(socket) {
    console.log('Yes, you did it!');
});
```
