### ISSUE TITLE
IO Address in Client

### ISSUE THREAD

**Issue by abdkaviani** [socketio/socket.io-website#239]
Hello
It works when I put this url in browser "http://localhost:3000", but bellow codes doesn't works with socket v4:

`<script src="http://localhost:3000/socket.io/socket.io.js"></script>`
`var socket = io.connect('http://localhost:3000');`
`socket.on('connect', function() {	`
`	socket.emit('join', ...);`
`}); `
`</script>`

It works with older version
Can you help me?

**Comment by abdkaviani** [comment]
`var socket = io.connect('http://localhost:3000', { transports : ['websocket'] });`
The problem is solved

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
