### ISSUE TITLE
There is no documentation about new functions in socket.io 4

### ISSUE THREAD

**Issue by salos1982** [socketio/socket.io-website#241]
I could not find documentation about new functions
```
socketsJoin
socketsLeave
disconnectSockets
fetchSockets
```
except migration guide https://socket.io/docs/v4/migrating-from-3-x-to-4-0/

**Comment by darrachequesne** [comment]
You are absolutely right! I have updated the documentation: https://socket.io/docs/v4/server-instance/#Utility-methods

Thanks for the heads-up!
