### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReplyError: EXECABORT Transaction discarded because of previous errors.

### ISSUE THREAD

**Issue by baisali-Pradhan** [socketio/socket.io-website#249]
When I entered the user name in the browser it shows the below error.

UnhandledPromiseRejectionWarning: ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (C:\Users\Baisali\OneDrive\Desktop\socket.io\examples\private-messaging\server\node_modules\redis-parser\lib\parser.js:179:12)
s\private-messaging\server\node_modules\redis-parser\lib\parser.js:302:14)   s\private-mes
(Use `node --trace-warnings ...` to show where the warning was created)      
(node:12892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without ahis error ori catch block, or by rejecting a promise which was not handled with .catch().  or by reject
To terminate the node process on unhandled promise rejection, use the CLI flaess on unhandg `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhttps://nodejhandled_rejections_mode). (rejection id: 1)
(node:12892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. Ineprecated. In the future, promise rejections that are not handled will terminjs process wiate the Node.js process with a non-zero exit code.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
