### ISSUE TITLE
socketio.docs has the current version missing in CDNJS

### ISSUE THREAD

**Issue by LeoTovell** [socketio/socket.io-website#256]
The version (4.1.1) doesn't exist on CDNJS. The others do work fine. Perhaps the server is down?

https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.1.1/socket.io.min.js

**Comment by darrachequesne** [comment]
That's weird indeed, cdnjs seems to be stuck to the 4.0.1 version: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/socket.io

It seems the bot was under maintenance a few days ago (https://status.cdnjs.com/incidents/sy4h7zqmpqfs), that might explain the issue.

**Comment by darrachequesne** [comment]
It seems to be fixed now, thanks for the heads-up :+1:
