### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at

### ISSUE THREAD

**Issue by mices** [socketio/socket.io-website#272]
I'm getting this error even though I get a normal response from ```curl "https://localhost:8000/socket.io/?EIO=4&transport=polling"``` I'm using this from a react BrowserRouter path inside a rails 6.1 app I didn't install or require cors because I don't see where/how I would

import io from "socket.io-client";

    useEffect(() => {
        socketRef.current = io.connect("http://localhost:8000", {
          withCredentials: true,
          extraHeaders: {
          "Access-Control-Allow-Origin": "*"
          },
          methods: ["GET","POST"]
        });

**Comment by darrachequesne** [comment]
Hi! Did you check: https://socket.io/docs/v4/handling-cors/

**Comment by mices** [comment]
That's where my code came from

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
