### ISSUE TITLE
A doubt about scale up socket.io

### ISSUE THREAD

**Issue by IgorDePaula** [socketio/socket.io-website#275]
1.If I have a nginx server or another load balancer with styck session I need of @socket.io/sticky? 
2. I need of a redis server for scale up?

I think want scale up with aws elastic container service with load balancer with sticky session. Is recommended? Is not? In cloud how I do?

**Comment by darrachequesne** [comment]
> 1.If I have a nginx server or another load balancer with styck session I need of @socket.io/sticky?

`@socket.io/sticky` is only needed if you have several workers on a single host, with the Node.js [cluster](https://nodejs.org/api/cluster.html) module.

If you have several hosts, you will indeed need a load-balancer with sticky session enabled.

See also: https://github.com/socketio/socket.io-sticky#notes

> 2. I need of a redis server for scale up?

You will need one of the adapters listed here: https://socket.io/docs/v4/adapter/

> I think want scale up with aws elastic container service with load balancer with sticky session. Is recommended?

Yes, that's a good setup. As usual, you'll have to loadtest it against your own use case.

**Comment by IgorDePaula** [comment]
Thank you very much for your attention.
