### ISSUE TITLE
Consider `connection` a reserved event

### ISSUE THREAD

**Issue by Rauno56** [socketio/socket.io-website#277]
[Documentation](https://github.com/socketio/socket.io-website/blob/master/source/docs/v4/emit-cheatsheet.md) does not mention it, but I cannot see a reason why using `connection` as a user emitted event should not be discouraged.

**Comment by darrachequesne** [comment]
The `connection` event is emitted by the Server, and not by the Socket instance, that's why it is not marked as reserved:

```js
io.on("connection", (socket) => {
  socket.on("disconnect", () => {
    /* ... */
  });
});
```

So you can totally use `connection` in your application.

That being said, you can't use `connection` with the `serverSideEmit()` method (along with `connect` and `new_namespace`, see [here](https://github.com/socketio/socket.io/blob/a4dffc6527f412d51a786ae5bf2e9080fe1ca63c/lib/namespace.ts#L46-L48)). Is that what you meant?

**Comment by Rauno56** [comment]
Thanks for the reply! I believe v2 did emit `connection` on Socket as well(if you are familiar)?
To conclude: `connection` is _technically_ a reserved event but only for Server - is that accurate?

**Comment by darrachequesne** [comment]
> I believe v2 did emit connection on Socket as well(if you are familiar)?

No, I don't think so.

Here is the detail of the emitted events:

- Socket instance on the server side v2/v3/v4:

  - disconnect
  - disconnecting

Reference: https://socket.io/docs/v4/server-api/

- Socket instance on the client side v2:

  - connect
  - disconnect
  - error
  - connect_error
  - connect_timeout
  - reconnect
  - reconnect_attempt
  - reconnecting
  - reconnect_error
  - reconnect_failed
  - ping
  - pong

Reference: https://socket.io/docs/v2/client-api/

- Socket instance on the client side v3/v4:
  
  - connect
  - disconnect
  - connect_error

Reference: https://socket.io/docs/v4/client-api/

See also: https://socket.io/docs/v4/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager

> To conclude: connection is technically a reserved event but only for Server - is that accurate?

"connection" is only a reserved event for the `serverSideEmit` functionality, which was added in `socket.io@4.1.0`. You can totally use it for your client-to-server communication.

```js
io.on("connection", (socket) => {
  // VALID
  socket.emit("connection");
  io.emit("connection");
  
  // INVALID (will throw an exception)
  io.serverSideEmit("connection");
});

```

**Comment by Rauno56** [comment]
I did some testing on top of your explanation and I think I got it now. Thank you, @darrachequesne, for your patience.

**v2** re-emits `connection` so `io.emit("connection");` in your example ends up looping until the maximum call stack is reached and is not actually emitted to the client. So I guess it is theoretically at least reserved, but doesn't throw? Maybe I'm getting stuck in terminology here.

**v3** on the other hand handles `connection` differently. It's kept separate from user-defined events with `serverSideEmit` that keeps the "RPC" layer separate from "internal" events.

**Comment by darrachequesne** [comment]
@Rauno56 you are absolutely right! `connection` can't be used by the Server instance in v2: https://github.com/socketio/socket.io/blob/e6b869738c73fa0ce9928974d823e50cc92f7a1a/lib/namespace.js#L22-L26

I updated the documentation: https://github.com/socketio/socket.io-website/commit/9982a2446fcd73c4979526a46b9d7e21f993bab7

Thanks a lot :+1:
