### ISSUE TITLE
cookie disappeared from handshake.headers

### ISSUE THREAD

**Issue by CRSylar** [socketio/socket.io-website#278]
We're using Socket.io to create a chat web app, and we need the cookie with the JWT that we give to client upon connection to autenticate it. (We are forced to do so).

We can't understand what is happening because we can find this cookie in "socket.handshake.headers.cookie" for all the day long.
after a small break we log in our pc and that value just disappeared from the socket handshake request… 
we don't know what to do, just fooling out…

Every kind of help will be appreciated a lot. Thanks.

ps. on the server side we are running Nestjs with Socket.io 2.4.1, 
on client side React with Socket.io-client 2.3.1

**Comment by darrachequesne** [comment]
That seems weird indeed.

> after a small break we log in our pc

That probably means the Socket.IO connection is closed and then reopened. Silly question, but... Is there any expiry set to the cookie? Can you see it being sent in the network tab of your browser?

**Comment by CRSylar** [comment]
after 2 days working on it (with nothing we're able to do to fix this) the problem just disappeared.. I'm closing this issue but can figure out what happened.
Probably was something with the browser, we'll try to study this weird happening

thanks

**Comment by darrachequesne** [comment]
OK, thanks for the update. If you ever find something, please ping me! :+1:
