### ISSUE TITLE
Emptying sendBuffer on connect doesn't seem to be working 

### ISSUE THREAD

**Issue by greenbea** [socketio/socket.io-website#282]
As per the documentation, https://socket.io/docs/v4/client-offline-behavior/ emptying the internal buffer will prevent buffered events from being sent out on reconnect, It doesn't seem to be working.

On my client-side I have

```
socket.on("connect", onConnect);
socket.on("connect_error", onConnectError);

onConnect() {
    socket.sendBuffer = [];
}

onConnectError() {
    setInterval(() => {
        if (!this.socket.connected) {
            socket.emit("test");
        }
    }, 2000)
}
```

on the server-side I have
```
  socket.on("test", () => {
      console.log("test");
  })
```

When the client goes offline and reconnects the buffer is not being emptied

**Comment by darrachequesne** [comment]
I could indeed reproduce, thanks.

The behavior has changed after [this commit](https://github.com/socketio/socket.io-client/commit/34f822f783c6985039c0733a96d1fab8f01b1edf), emptying the `sendBuffer` in the "connect" event is not possible anymore.

**Comment by darrachequesne** [comment]
I've updated the documentation: https://socket.io/docs/v4/client-offline-behavior/

Thanks for the heads-up :+1:
