### ISSUE TITLE
io.in(room).emit() not working version 4.x

### ISSUE THREAD

**Issue by 1omercohen** [socketio/socket.io-website#283]
Hello,

we have to function for to send to room a message
to - send to all except  the sender
in - send to all include the sender

I what to send also the sender, I am using in and sender does not get the event back

from your documentation 
` // to all clients in room1
  io.in("room1").emit(/* ... */);`

**Comment by darrachequesne** [comment]
Hi! That sounds weird, could you please provide a way to reproduce?

Either with https://stackblitz.com/edit/socketio-base?file=index.js or https://github.com/socketio/socket.io-fiddle.

Thanks in advance.

**Comment by 1omercohen** [comment]
I can share some of my code but I tried to build in https://stackblitz.com/edit/socketio-base?file=index.js
is too match working or test it with your self or live with this bug
