### ISSUE TITLE
Best way to tell two users apart?

### ISSUE THREAD

**Issue by gillerby** [socketio/socket.io-website#284]
e.g., User A connects to the page, then due to poor internet connection disconnects, then reconnects.

Supposing socket.io's reconnect feature fails, how can I check whether this user is the same as user A?

IP is not a reliable method, since on top two users in the same house can have the same IP and this wouldn't allow to differentiate them.

The socket.id seems to change when you reload the page for example, so for reconnection doesn't seem ideal.

**Comment by HeroOfOdyssey** [comment]
have client send a cookie based identifier, preferrably on top of something like a server verified jwt to ensure no MITM or cookie stealing occurs.

**Comment by darrachequesne** [comment]
For future readers:

Cookie is indeed the way to go.

Please check our example with express session: https://socket.io/how-to/use-with-express-session
