### ISSUE TITLE
match any namespace

### ISSUE THREAD

**Issue by Zibri** [socketio/socket.io-website#287]
if I do:

```
io.on("connection", (socket) => {
  console.log(`connect ${socket.id} on ${socket.nsp.name}`);
})
```

and then in the cllient I do:

`s=io();`

I can see that in the log.
but if I do:

`s=io("/randomstring")`
I don't see the log.

if instead I do:

if I do:

```
io.of(/.*/).on("connection", (socket) => {
  console.log(`connect ${socket.id} on ${socket.nsp.name}`);
})
```

it matches this: `s=io("/randomstring")`
but not this: `s=io()`

how to match both in a single line?

**Comment by darrachequesne** [comment]
Hi! There is currently no way to do this in a single line, but you should be able to reuse the connection handler:

```js
const onConnection = (socket) => {
  console.log(`connect ${socket.id} on ${socket.nsp.name}`);
};

io.on("connection", onConnection);
io.of(/.*/).on("connection", onConnection);
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
