### ISSUE TITLE
Custom protocol links cause the websocket connection to silently close

### ISSUE THREAD

**Issue by fjeldstad** [socketio/socket.io-website#292]
With the new `closeOnBeforeunload` behavior, the websocket connection is by default silently closed when a user clicks a custom protocol link (as that triggers the `beforeunload` event). This tripped us over pretty badly after upgrading to 4.1.0. Would probably be a good idea to mention this in the docs for the setting - we didn't actively use `beforeunload` for anything and were not aware that custom protocol links would trigger the event.

**Comment by darrachequesne** [comment]
For future readers:

Starting with version `4.7.1`, the `closeOnBeforeunload` option now defaults to `false`, in order to prevent those kind of surprises.

Reference: https://socket.io/docs/v4/client-options/#closeonbeforeunload
