### ISSUE TITLE
22th century SSL

### ISSUE THREAD

**Issue by b1tw0rker** [socketio/socket.io-website#294]
I am quite not sure. But we are living in the 22th century. Most system working fine with SSL except socket.io.
All you example coedes are still based on http. (non SSL)
This should be changed immeditaly...

**Comment by darrachequesne** [comment]
> But we are living in the 22th century

Are you from the future?

> Most system working fine with SSL except socket.io.

Did you have any issue with Socket.IO and SSL?

> All you example coedes are still based on http

Using SSL is just a matter of getting a SSL certificate and provide an HTTPS server to the Socket.IO server constructor, as detailed here: https://socket.io/docs/v4/server-initialization/#With-an-HTTPS-server

Could you please provide more details?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
