### ISSUE TITLE
Demo -- I get video working on all clients, but no audio

### ISSUE THREAD

**Issue by swarr2** [socketio/socket.io-website#299]
//////// MAIN FUNCTIONS /////////////
    async produce(type, deviceId = null)
    {
        let mediaConstraints = {}
        let audio = false
        let screen = false
        switch (type)
        {
            case mediaType.audio:
                console.log ("audio")
                mediaConstraints = {
                    audio: {
                        deviceId: deviceId
                    },
                    video: false
                }
                audio = true
                break
            case mediaType.video:
                mediaConstraints = {
                    audio: true,
                    video: {
                        width: {
                            min: 640,
                            ideal: 1920
                        },
                        height: {
                            min: 400,
                            ideal: 1080
                        },
                        deviceId: deviceId
                    }
                }
                break
            case mediaType.screen:
                mediaConstraints = false
                screen = true
                break;
            default:
                return
                break;
        }
        if (this.producerLabel.has(type)) {
            console.log('producer already exists for this type ' + type)
            return
        }
        let stream;
        try {
            //stream = screen ? await navigator.mediaDevices.getDisplayMedia() :
            stream =  await navigator.mediaDevices.getUserMedia(mediaConstraints)
            //var track = audio ? stream.getAudioTracks()[0] :
            var track = stream.getVideoTracks()[0]
            const params = {
                track
            };
          producer = await this.producerTransport.produce
              (params)
          console.log('producer', producer, " params "+
             JSON.stringify(params))
            this.producers.set(producer.id, producer)

            let elem
            if (!audio)
            {
                elem = document.createElement('video') //local video
                elem.srcObject = stream
                elem.id = producer.id
                elem.playsinline = true
                elem.autoplay = true
                elem.className = "vid"
                this.localMediaEl.appendChild(elem)  //local video
                videos[videoNum]=elem;//works with 0
                videos[videoNum].setAttribute("muted",false);
                videoNum++;
            }
            producer.on('trackended', () => {
                this.closeProducer(type)
            })
            producer.on('transportclose', () => {
                console.log('producer transport close')
                if (!audio) {
                    elem.srcObject.getTracks().forEach(function (track)
                    {
                        track.stop()
                        videoNum--;
                    })
                    elem.parentNode.removeChild(elem)
                }
                this.producers.delete(producer.id)

            })

            producer.on('close', () => {
                console.log('closing producer')
                if (!audio) {
                    elem.srcObject.getTracks().forEach(function (track)
                    {
                        track.stop()
                        videoNum--;
                    })
                    elem.parentNode.removeChild(elem)
                }
                this.producers.delete(producer.id)

            })

            this.producerLabel.set(type, producer.id)

            switch (type) {
                case mediaType.audio:
                    this.event(_EVENTS.startAudio)
                    break
                case mediaType.video:
                    this.event(_EVENTS.startVideo)
                    break
                case mediaType.screen:
                    this.event(_EVENTS.startScreen)
                    break;
                default:
                    return
                    break;
            }
        } catch (err) {
            console.log(err)
        }
        doCanvas();//doTheVideos()
    }// end produce

 async consume(producer_id)
 {
        this.getConsumeStream(producer_id).then(function ({
            consumer,
            stream,
            kind
           }) {

            this.consumers.set(consumer.id, consumer)
            let elem;
            if (kind === 'video')
            {
                elem = document.createElement('video')
                elem.srcObject = stream
                elem.id = consumer.id
                elem.playsinline = false
                elem.autoplay = true
                elem.className = "vid"
                console.log("consumer.id "+consumer.id)
                this.remoteVideoEl.appendChild(elem) //remote video
                videos[videoNum]=elem;//works with 0
                videos[videoNum].setAttribute("muted",false);
                videoNum++;
                console.log ("consumer videos.length "+videos.length+" videoNum "+videoNum)
            }
            else
            {
                elem1 = document.createElement('audio')
                elem1.srcObject = stream
                elem1.id = consumer.id
                elem1.playsinline = false
                elem1.autoplay = true
                this.remoteAudioEl.appendChild(elem1)//remote audio
            }

            consumer.on('trackended', function ()
            {
                this.removeConsumer(consumer.id)
                videoNum--;
            }.bind(this))
            consumer.on('transportclose', function ()
            {
                this.removeConsumer(consumer.id)
                videoNum--;
            }.bind(this))
        }.bind(this))
    }//end consume

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
