### ISSUE TITLE
io is not a function, and Server is not a constructor

### ISSUE THREAD

**Issue by storjak** [socketio/socket.io-website#310]
I have a web app I'm building, and the front and the back end are hosted on completely different services.  The front end files are all also completely isolated and will be packaged so I can't import Socket.IO from a URL, or with the `script` element.  I'm bundling all my html pages and JS files in one directory, which is then being hosted and served.  Basically, my HTML and all the associated JS is isolated and is all being hosted and imported locally.  The HTML page can be accessed normally from a server request, the root JS file is loaded, which imports a few other JS files including Socket.IO, which then is supposed to use Socket.IO to connect to my server upon a page event.

On the page I'm working on, I can't get Socket.IO to work at all.
```javascript
const { Server } = import("./socket.io.min.js"); // I've tried a variety of these import methods,
const Server     = import("./socket.io.min.js"); // I'm not using all of these at once.
const { io }     = import("./socket.io.min.js"); // The JS file I'm importing here isn't a module,
const io         = import("./socket.io.min.js"); // so I can't use the "import * as xyz" method.

const io = new Server({ // produces the error "Server is not a constructor"
    serveClient: false,
    path: "http://localhost:3001",
    withCredentials: true,
    autoConnect: false
});
const socket = io('http://localhost:3001', { // produces the error "io is not a function"
    withCredentials: true,
    autoConnect: false
});
```
None of these combinations fix any of the errors I'm getting.  If I try to use `io` as a function I get the error `io is not a function`, and if I try to start a new instance using the `new Server` method, I get the error `Server is not a constructor`.

Yes, I also have `socket.io.min.js.map` in the same directory as `socket.io.min.js`, I'm not getting any errors from that.

I believe `io` is registered as a global function when using the `script` element import method, but because I have to import my JS files instead of have JS inline, that doesn't work for me in this instance.

Am I doing something wrong here or did I find a bug?  I'm using v4.4.0.

**Comment by darrachequesne** [comment]
It seems you are mixing up the client and the server package.

Server:

```js
import { Server } from "socket.io";

const io = new Server();
```

Reference: https://socket.io/docs/v4/server-initialization/

Client:

```js
import { io } from "socket.io-client";

const socket = io("https://mydomain.com");
```

Reference: https://socket.io/docs/v4/client-initialization/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
