### ISSUE TITLE
Can't scroll docs pages unless JavaScript is disabled.

### ISSUE THREAD

**Issue by Enteleform** [socketio/socket.io-website#344]
Seems like it might be an issue with Docusaurus & Chromium (*happens @ Chrome & Edge*). I've encountered this before and figured I'd open an issue here since it seems to be widespread and I don't remember what the other sites were.

Scrolling seems to work fine on FireFox and Safari.

![Scroll](https://user-images.githubusercontent.com/10906415/176339392-22ec423d-7601-457e-a2b9-3e47517b90f0.gif)

**Comment by takapiro99** [comment]
This phenomenon is happening to me as well...

**Comment by Titancube** [comment]
Also happening to me while using Edge on Mac

**Comment by kostDev** [comment]
Same in a chrome 104.0.5112.101

**Comment by marcpicaud** [comment]
Same here

**Comment by darrachequesne** [comment]
That's really weird. I guess we need to upgrade to the latest docusaurus version.

Related: https://github.com/facebook/docusaurus/pull/7057

**Comment by darrachequesne** [comment]
Hi everyone, we have migrated to Docusaurus version `2.3.1`, from `2.0.0-beta.15`. Could you please check if this issue is fixed?

**Comment by marcpicaud** [comment]
Hi @darrachequesne , I just tested with Chrome on a Mac and it looks good 🎉  Thanks for the fix

**Comment by darrachequesne** [comment]
@marcpicaud thanks a lot for the feedback!

I'm closing this then, please ping me if needed.
