### ISSUE TITLE
Chat example broken (Access-Control-Allow-Origin etc.)

### ISSUE THREAD

**Issue by 1j01** [socketio/socket.io-website#35]
`GET http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=LVesgWJ`
`XMLHttpRequest cannot load http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=LVer5WW. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://socket.io' is therefore not allowed access. The response had HTTP status code 502.`

`GET http://chat.socket.io/socket.io/socket.io.js net::ERR_INCOMPLETE_CHUNKED_ENCODING`

`Uncaught ReferenceError: io is not defined(…)`

The polling error pair repeats and later on there's also
`GET http://platform.twitter.com/widgets.js net::ERR_NAME_RESOLUTION_FAILED`

**Comment by 1j01** [comment]
It's broken on http://socket.io/demos/chat/ as well as http://chat.socket.io/ which just gets
`http://chat.socket.io/socket.io/socket.io.js`
`Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING`
`Uncaught ReferenceError: io is not defined`
`http://chat.socket.io/favicon.ico`
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by ha7ilm** [comment]
Me too. Getting something like this:

> XMLHttpRequest cannot load http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=--------. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://socket.io' is therefore not allowed access. The response had HTTP status code 502.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
