### ISSUE TITLE
Upgrade mechanism clarification

### ISSUE THREAD

**Issue by qstiegler** [socketio/socket.io-website#351]
I'm currently running into timeout issue related to the long polling. While debugging it, I looked into the [documentation to see why long polling is used in the first place](https://socket.io/docs/v4/how-it-works/#upgrade-mechanism).

There are two wordings that are tripping me up:

> From the user perspective, an unsuccessful WebSocket connection can translate in **up to at least 10 seconds** of waiting for the realtime application to begin exchanging data

Is it "up to 10 seconds" or "at least 10 seconds"? Those two are seemingly contradicting each other.

Which follows this part

> While WebSocket is clearly the best way to establish a bidirectional communication, experience has shown that it is not always possible to establish a WebSocket connection, due to corporate proxies, personal firewall, antivirus software...

This sounds like sometimes it's not possible for the connection to be setup at all. Is it meant in a way that it's just a delay?

I'd be happy to supply a pull request to clarify this in the documentation when anyone has more information on this or can guide me to external links explaining the root cause in more detail 🙂

**Comment by darrachequesne** [comment]
@qstiegler you are right, the wording was indeed wrong, this should be fixed by https://github.com/socketio/socket.io-website/commit/77e880194deab70d9daec689f64c0d9918d4fa14. Glad to see that some people are actually reading the documentation :smile:
