### ISSUE TITLE
Unofficial examples section

### ISSUE THREAD

**Issue by tiagofabre** [socketio/socket.io-website#36]
Hello,

After spend a lot of time trying to make a cluster with _socket.io + socket.io-redis_ I would like to share my experience with the community and my suggestion is to add a new section in the site called "**Unofficial examples**" to share this kind of projects. To make this cluster work was a difficult experience for me and I found a lot of people with the same problems. 

In this section the authors of open source projects could share some links with solutions explaining more about _socket.io_ and details about that.

What do you think ?

**Comment by darrachequesne** [comment]
Could you check the following examples?
- [nginx](https://github.com/socketio/socket.io/pull/2817)
- [haproxy](https://github.com/socketio/socket.io/pull/2818)
- [httpd](https://github.com/socketio/socket.io/pull/2819)

Reviews / other examples are welcome!

**Comment by tiagofabre** [comment]
That is great! Thank you @darrachequesne
