### ISSUE TITLE
Issue on links on 'Options' section on client-initialization.md 

### ISSUE THREAD

**Issue by strykerin** [socketio/socket.io-website#361]
The links are on the wrong case so when clicking on the links the user is not being redirected

example:

`docs/v3/client-initialization/#extraHeaders` should be replaced to `docs/v3/client-initialization/#extraheaders`

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-website/commit/11b5b25e74ce33d793027cc7df2fd0015667c0c8.
