### ISSUE TITLE
Engine.IO: Typo in heartbeat documentation 

### ISSUE THREAD

**Issue by Totodore** [socketio/socket.io-website#378]
I'm currently working on an Engine.IO implementation and while reading the docs about heartbeat I found this :

> If the server does not receive a pong packet back, then it SHOULD consider that the connection is closed.
> Conversely, if the client does not receive a *pong* packet within pingInterval + pingTimeout, then it SHOULD consider that the connection is closed.

If I understood the protocol correctly I think there a typo here and that it is  : 
> Conversely, if the client does not receive a *ping* packet

Because client should never receive pong packet.

**Comment by darrachequesne** [comment]
Hi! That's indeed a typo, good catch :+1: 

This should be fixed by https://github.com/socketio/socket.io-website/commit/5254ce5d4a764a47e1531230a1825869d9493b3d.
