### ISSUE TITLE
unable to access http://socket.io/docs/client-api/

### ISSUE THREAD

**Issue by e-cloud** [socketio/socket.io-website#40]

**Comment by abramz** [comment]
Guys, your client docs have been broken for days, please fix ASAP.

Go to http://socket.io/docs/client-api/

Nothing renders, no logs to console, no network errors.

**Comment by JacksonBates** [comment]
@abramz -- A work around:

Set your user agent in Chrome to something like Android browser. It still works on mobile:

![image](https://cloud.githubusercontent.com/assets/4337740/21163902/d57bc99c-c1e9-11e6-9a79-b5cc72431546.png)

Hat-tip to @jenovs

**Comment by abramz** [comment]
Your docs have been broken for at least 9 days.

@rase- @rauchg @julianvmodesto @Projjol @blazedd @sergejmueller @davidcelis

**Comment by davidcelis** [comment]
@abramz Seriously, you @mentioned every contributor to this site? Almost everybody on that list has _one commit_ to the repo. Mine was a typo fix. Come on, man.

**Comment by barryvdh** [comment]
Seems to be that the HTML is cut off at line 40:
`<script type='text/javascript' src='http://socket.io/wp-includes/js/jque`

**Comment by coagmano** [comment]
It's pretty bloody awful for the client docs to be down for over a week though

**Comment by ceelian** [comment]
Still offline

**Comment by darrachequesne** [comment]
That is a [known](https://github.com/socketio/socket.io/issues/2823) issue, please refer to the documentation on [Github](https://github.com/socketio/socket.io-client/blob/master/docs/API.md) until it is fixed.

**Comment by ceelian** [comment]
Didn't know, thank you!

**Comment by darrachequesne** [comment]
@ceelian you're welcome, sorry for the inconvenience!

**Comment by jamime** [comment]
Do why know why it breaks, I'm assuming a wordpress issue? This site could easily be statically generated and hosted on github pages.

**Comment by ZudoMC** [comment]
Still dead, can we have a response please?

**Comment by barryvdh** [comment]
See https://github.com/socketio/socket.io/issues/2823
Seems to be trouble with control over the site.
Docs are also here: https://github.com/socketio/socket.io-client/blob/master/docs/API.md

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
