### ISSUE TITLE
Socket.IO home page still mentions "Download v1.4.5"...

### ISSUE THREAD

**Issue by richb-hanover** [socketio/socket.io-website#41]
... yet github seems to be up to 1.7.2. This is confusing, to say the least...

Perhaps the button could say, "Download Socket.io"...

Although the page at http://socket.io/download/ has a link to your CDN that specifies 1.4.5... It'd be nice to have a consistent story.

**Comment by EddieOne** [comment]
I assumed everything newer was a development branch. But actually it seems just nobody updated the links. Can you submit a pull @richb-hanover

**Comment by T0toro** [comment]
Hi,

download links are stored in a database, they can only be updated from wordpress admin panel.

**Comment by EddieOne** [comment]
Oh, I guess they need to be added to the cdn. So is 1.4.5 the latest stable version?

**Comment by richb-hanover** [comment]
> Oh, I guess they need to be added to the cdn. So is 1.4.5 the latest stable version?

@darrachequesne, @rauchg  - Would either of you be able to clarify the status of socket.io versions?

- socket.io website button says "Download 1.4.5" (from 26 Jan 2016 - a year ago)
- Most recent file on CDN appears to be 1.4.8 https://cdn.socket.io/socket.io-1.4.8.js (from 23 Jun 2016 - six months ago)
- History.md file lists 1.7.2 (from 11 Dec 2016 - two months ago)

Thanks!

**Comment by EddieOne** [comment]
I'm not exactly sure, I tested 1.7.2 and it seemed to contain some breaking changes with 1.3.x and 1.4.x.
@darrachequesne  can you clarify for us here? I guess 1.7.2 is the latest stable but your [waiting to be elected](https://github.com/socketio/socket.io/issues/2823). 😛

**Comment by darrachequesne** [comment]
As said [here](https://github.com/socketio/socket.io/issues/2823#issue-200589184), I've currently no control over the website so it is unfortunately not up-to-date.

The latest stable release is indeed 1.7.2 (CDN: https://cdnjs.com/libraries/socket.io).

**Comment by etroynov** [comment]
@darrachequesne Who control website?

**Comment by rauchg** [comment]
Technically it's me, but really it's also tied to Automattic who now owns
the domain name socket.io.
I'll sort this out so that the community can own the domain name

– @rauchg <https://twitter.com/rauchg>

**Comment by richb-hanover** [comment]
Thank you!

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.

**Comment by richb-hanover** [comment]
Congratulations! And thanks!
