### ISSUE TITLE
Dark theme not applied by default based on the user OS/Browser preference

### ISSUE THREAD

**Issue by kumaravel95** [socketio/socket.io-website#410]
ug: If a user applied dark theme in OS/Browser preference, when user lands for the first time, By default, LIGHT theme is applied.

Fix:
docusaurus have the config to apply theme based on the user's preference
REF: https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme

Note: docusaurus website respects the user's preference theme

Pullrequest is created to fix this issue: https://github.com/socketio/socket.io-website/pull/409

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-website/pull/409.
