### ISSUE TITLE
Sponsers logo not visible in dark mode

### ISSUE THREAD

**Issue by AmanSingh81757** [socketio/socket.io-website#418]
In dark mode theme some of the sponsors logo images are not visible as the background color is similar in shade to text of the logo.
Screenshot for reference:
![image](https://github.com/socketio/socket.io-website/assets/102822868/42a3a96c-485b-4524-9c0a-77b922c37600)
which looks like this in light theme
![image](https://github.com/socketio/socket.io-website/assets/102822868/3cceeab9-3260-4329-a802-bc44c4389387)
Some more screenshots:
In dark theme:
![image](https://github.com/socketio/socket.io-website/assets/102822868/e1d3a79c-dffb-4cc9-9ea7-baef24fe9217)
In light theme:
![image](https://github.com/socketio/socket.io-website/assets/102822868/9d8f3214-f315-4893-9929-d68357a5547f)

This is due to the images being png format instead of jpg

**Comment by prathameshgaikwad** [comment]
Can you assign this to me?

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io-website/commit/704b9de11c8088d5eeac3fb156b230496bc8df9c#diff-7219cbaf3b8deb9499447fa7d8b84a760cdfb348e2915f8e682e3a7456b0194eR40.
