### ISSUE TITLE
Update: Hover/Transition Over Get started and Documentation Buttons!!

### ISSUE THREAD

**Issue by DeepRahangdale** [socketio/socket.io-website#419]

**Comment by darrachequesne** [comment]
Hi! Could you please explain the issue with those buttons?

**Comment by DeepRahangdale** [comment]
lack the transition, quite simple!! 
pop up transition while hovering over the button would be great for user experience.

**Comment by prathameshgaikwad** [comment]
https://github.com/socketio/socket.io-website/assets/37247788/56c8e557-a6d0-46bb-a11f-2b4e1a0118a1

like this?

**Comment by darrachequesne** [comment]
Done in https://github.com/socketio/socket.io-website/commit/467f52dd0448182e6dae27793b1a22b3f81aac87.

Thanks for the heads-up :+1:
