### ISSUE TITLE
Chat demo downloading javascript over HTTP

### ISSUE THREAD

**Issue by embray** [socketio/socket.io-website#42]
On http://socket.io/get-started/chat/ the "Emitting Events" section displays some sample code for the client side that includes:

```
<script src="http://code.jquery.com/jquery-1.11.1.js"></script>
```

Since a lot of beginners are going to be reading this guide we probably shouldn't give such bad advice, opting instead for https.  Incidentally the example code in https://github.com/socketio/socket.io/tree/master/examples/chat is correct; it's just the website that's out of date.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
