### ISSUE TITLE
hyperlink points to French Wikipedia page

### ISSUE THREAD

**Issue by aarowman** [socketio/socket.io-website#423]
On https://socket.io/docs/v4/emitting-events/#volatile-events, it references UDP, and the hyperlink is to Wikipedia in French:

```md
(a bit like [UDP](https://fr.wikipedia.org/wiki/User_Datagram_Protocol), in terms of reliability).
```

It points to `fr.wikipedia.org`, but it should simply be `wikipedia.org`, and wikipedia should redirect to the correct language. Either that or use `en.wikipedia.org` so it's English

**Comment by darrachequesne** [comment]
Good catch, thanks! This should be fixed now.
