### ISSUE TITLE
Client API documentation (http://socket.io/docs/client-api/) completely blank

### ISSUE THREAD

**Issue by hroptatyr** [socketio/socket.io-website#43]
The page http://socket.io/docs/client-api/ wouldn't display anything at all.

The problem seems to be here:

     <script type='text/javascript' src='http://socket.io/wp-includes/js/jque
               End of file reached when inside an attribute value. Ignoring tag.

**Comment by dkoston** [comment]
Any updates on this? The documentation has been completely down for almost 2 weeks.

**Comment by abramz** [comment]
This is a duplicate of [this](https://github.com/socketio/socket.io-website/issues/40) which has been open since Dec 5, 2016.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
