### ISSUE TITLE
(http:|https:)//socket.io site down?

### ISSUE THREAD

**Issue by yshing** [socketio/socket.io-website#45]
The official website seems to be down for a long time..
`ERR_CONNECTION_TIMED_OUT`

**Comment by chief10** [comment]
For a working link in the meantime, try wayback machine: https://web.archive.org/web/20170216002313/http://socket.io/

**Comment by Mattchewone** [comment]
Anyone know why it is down?

Still showing as down now.

**Comment by akkhan20** [comment]
Update: Still down!

**Comment by Ztrains** [comment]
Been trying to get on for a few days now.  Why has the site been down for over 2 weeks?

**Comment by milad1367** [comment]
whats hapen?! i need socket for my project.i need start learning socket programing in nodjs but it site is down!!!!

**Comment by darrachequesne** [comment]
The domain name is owned by Automattic (rauchg's previous company), hence the current mess.

Please use https://socketio.now.sh/ until it is fixed.

**Comment by milad1367** [comment]
tnx man

**Comment by akkhan20** [comment]
FYI: The Actual domain is back i.e Socket.io[(https://socket.io/)]

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
