### ISSUE TITLE
https://socket.io/get-started/chat/ isn't found

### ISSUE THREAD

**Issue by imam** [socketio/socket.io-website#46]

**Comment by Haskaalo** [comment]
Socket.IO website and CDN have been down for days.

**Comment by imam** [comment]
@Haskaalo the socket.io site already up, but the getting started page isn't

**Comment by Haskaalo** [comment]
@imam Yes, but also their CDN doesnt work.

**Comment by cicnavi** [comment]
I was just thinking to try out socket.io, but their site is down. Is it worth to try it out anyway? What's going on...?

**Comment by Haskaalo** [comment]
@cicnavi I recommend downloading the [socket.io-client](https://www.npmjs.com/package/socket.io-client) with bower or clone it instead of using the CDN at the moment.

**Comment by yshing** [comment]
@imam http://www.downforeveryoneorjustme.com/socket.io
socket.io website has been down for a long time..

**Comment by imam** [comment]
@yshing the site was running for several hours back when I opened this issue, and only `Getting started` page that was still down. Now it's down completely again, I'll close this issue.

**Comment by imam** [comment]
Good news for everyone, socket.io is up! :smiley_cat:
