### ISSUE TITLE
Replace missing browser usage example

### ISSUE THREAD

**Issue by therealplato** [socketio/socket.io-website#47]
Hi I came to verify how to connect to socket.io while writing a stackoverflow answer

When I last used the project, there were obvious examples showing the minimal code required on server and browser.

I now only see the server example. Even after navigating to Get Started, Demos and Docs I do not see a usage example for how to source and instantiate the `io` object.

**Comment by darrachequesne** [comment]
Did you take a look at https://socket.io/docs/ ?

**Comment by therealplato** [comment]
Thanks. I did look there. I didn't see it so I continued to Docs > Client API. Looking again I found it below the fold.

I preferred the old site design with server and client examples that stood out on home page with no navigation or searching
