### ISSUE TITLE
Adding search to the documentation

### ISSUE THREAD

**Issue by Haroenv** [socketio/socket.io-website#58]
Hey 👋 

I think it would be nice to add search to the documentation and tutorials, since it's quite a bit faster than going through different pages. 

At Algolia we offer [DocSearch](https://community.algolia.com/docsearch/) as a free option for community to search within documentation. If you agree I'd like to set it up here. 

Enjoy your day ❇️

**Comment by phrawzty** [comment]
Hello! My name is Dan and and I'm a developer advocate at Algolia. I just wanted to throw my hat in  for [DocSearch](https://community.algolia.com/docsearch/) as well. We already power the search for some 400 projects, and I'd love to see Socket.IO among them. 😄 If you have any questions at all, please don't hesitate to ask. Cheers!
