### ISSUE TITLE
Production Server SSL within a folder

### ISSUE THREAD

**Issue by canado** [socketio/socket.io-website#75]
Hello,

Thank you for this tools, I made it work on localhost, but I would like to make it work on my production server (Apache) with SSL activated and within a subfolder

example
mywebsite.com/websocket

Thanks

**Comment by AnonymousWebHacker** [comment]
Reverse proxy from nginx or apache2

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
