### ISSUE TITLE
Docs: rename "Express Framework"

### ISSUE THREAD

**Issue by daguej** [socketio/socket.io-website#8]
In the docs, the section about using socket.io with Express 2.x is called ["Using with the Express Framework"](http://socket.io/docs/#using-with-the-express-framework)

[This leads to confusion](http://stackoverflow.com/q/24377654/201952), and should be renamed "Using with Express 2.x".

**Comment by JetForMe** [comment]
I agree.

**Comment by dimirc** [comment]
+1

**Comment by puckbag** [comment]
+1

**Comment by lucasqiu** [comment]
+1

**Comment by panuhorsmalahti** [comment]
+1
