### ISSUE TITLE
Documentation Example did not work

### ISSUE THREAD

**Issue by archiebaer** [socketio/socket.io-website#84]
[https://socket.io/docs/client-api/#With-a-self-signed-certificate](https://socket.io/docs/client-api/#With-a-self-signed-certificate)

I spent about an hour trying to get the example to work, but I needed to use
`
const app = require('express')();
const server = require('https').createServer({
  key: fs.readFileSync('server-key.pem'),
  cert: fs.readFileSync('server-cert.pem')
}, app);`

instead.

Credit: I figured this out thanks to [this article](https://medium.com/@yash.kulshrestha/using-lets-encrypt-with-express-e069c7abe625).

**Comment by darrachequesne** [comment]
It seems the documentation doesn't include an example with both express and a self-signed certificate.

Could you please open a pull request? Thanks!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
