### ISSUE TITLE
how to update docs?

### ISSUE THREAD

**Issue by calendee** [socketio/socket.io-website#9]
Seems this is a wordpress site.  So, the community can't help fix mistakes in the docs.

See : http://socket.io/docs/server-api/#socket#join(name:string[,-fn:function]):socket

There is an invalid link to : https://github.com/socket.io/socket.io-adapter in

> that has been configured (see Server#adapter above), defaulting to
> socket.io-adapter.

**Comment by 1j01** [comment]
+1, I would like to send PRs for some of these issues but I can't.

**Comment by sbedulin** [comment]
+1 , wanted to fix a couple of typos and grammar.

**Comment by focusaurus** [comment]
Here's a small change I'd like to make to help beginners who are often utterly bewildered by the numerous modules, objects and functions they need to instantiate and connect properly to get the "get started" chat application wired up (express, http, the express app, the http server, the socket.io instance, etc)

> var http = require('http').Server(app);

Please don't make this confusing. The variable `http` should refer to the core `http` module. Then separately create the server instance

    var http = require('http');
    var server = http.createServer(app);

(and adjust the rest of the example accordingly)

**Comment by darrachequesne** [comment]
The website is now stored in this repository, do not hesitate to open pull request if you see something missing / incorrect.
