### ISSUE TITLE
Socket.io dotnet client deprecated and netstandard client is missing

### ISSUE THREAD

**Issue by guylando** [socketio/socket.io-website#94]
Currently you list https://github.com/Quobject/SocketIoClientDotNet as the dotnet client however:
1. That library DOES NOT support dotnet core or dotnet standard
2. That library is deprecated

Please update the documentation with some working solution.
For example adding "/socket.io/?EIO=3&transport=websocket" url suffix while using some c# websockets library such as https://github.com/kerryjiang/WebSocket4Net

**Comment by darrachequesne** [comment]
For future readers, please check https://github.com/doghappy/socket.io-client-csharp.
